openapi: 3.0.3
info:
  title: Music info
  version: 0.0.1
servers:
  - url: 'http://localhost:8888'
paths:
  /:
    post:
      summary: Get songs with pagination and serching parametres
      parameters:
        - name: limit
          description: Count of songs in one page
          in: query
          schema:
            type: integer
        - name: page
          description: Page number
          in: query
          schema:
            type: integer
      requestBody:
        description: JSON have to contain information for searching
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Song'   
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SongHeader'
        '400':
          description: Bad request
        '500':
          description: Internal server error  
  /lyrics:
    get:
      summary: Get song's lyrics with pagination
      parameters:
        - name: limit
          description: Count of couplets in one page
          in: query
          schema:
            type: integer
        - name: page
          description: Page number
          in: query
          schema:
            type: integer
        - name: group
          in: query
          schema:
            type: string
          required: true
        - name: song
          in: query
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error  
  /delete:
    delete:
      summary: Delete the song by "group" and "song" parameters
      parameters:
        - name: group
          in: query
          required: true
          schema:
            type: string
        - name: song
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /change:
    post:
      summary: Change song's data
      parameters:
        - name: group
          in: query
          required: true
          schema:
            type: string
        - name: song
          in: query
          required: true
          schema:
            type: string
      requestBody:
        description: JSON have to contain fields that you want to change
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Song'   
      responses:
        '200':
          description: Ok
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /info:
    post:
      summary: Create new song
      requestBody:
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Song'         
      responses:
        '200':
          description: Ok
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
    get:
      summary: Returns song's detail by "group" and "song" parameters
      parameters:
        - name: group
          in: query
          required: true
          schema:
            type: string
        - name: song
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongDetail'
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    Song:
      anyOf:
        - $ref: '#/components/schemas/SongHeader'
        - $ref: '#/components/schemas/SongDetail'
      type: object
    SongHeader:
      required:
        - group
        - song
      type: object
      properties:
        group:
          type: string
          example: Muse
        song:
          type: string
          example: Supermassive Black Hole
    SongDetail:
      required:
        - releaseDate
        - text
        - link
      type: object
      properties:
        releaseDate:
          type: string
          example: 16.07.2006
        text:
          type: string
          example: Ooh baby, don't you know I suffer?\nOoh baby, can you hear me moan?\nYou caught me under false pretenses\nHow long before you let me go?\n\nOoh\nYou set my soul alight\nOoh\nYou set my soul alight
        link:
          type: string
          example: https://www.youtube.com/watch?v=Xsp3_a-PMTw
